# Generated by Django 5.1.1 on 2024-09-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='tags',
            field=models.CharField(max_length=100),
        ),
    ]
